
% primaryTable = [reconstructionMatrix, multiplexingPerp];

sankeyStruct.visual.error = ...
    sum(primaryTable.Error(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Disable(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Enable(primaryTable.Visual == 1,:) == 0);

sankeyStruct.visual.posConflict = ...
    sum(primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.Error(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Disable(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Enable(primaryTable.Visual == 1,:) == 0);


sankeyStruct.visual.negConflict = ...
    sum(primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.Error(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Disable(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Enable(primaryTable.Visual == 1,:) == 0);

sankeyStruct.visual.disable = ...
    sum(primaryTable.Disable(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.Error(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Enable(primaryTable.Visual == 1,:) == 0);

sankeyStruct.visual.enable = ...
    sum(primaryTable.Enable(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.Error(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Disable(primaryTable.Visual == 1,:) == 0);

sankeyStruct.visual.visual = ...
    sum(primaryTable.Visual(primaryTable.Visual == 1,:) == 1 & ...
    primaryTable.Error(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.PositiveConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.NegativeConflict(primaryTable.Visual == 1,:) == 0 & ...
    primaryTable.Enable(primaryTable.Visual == 1,:) == 0 &...
    primaryTable.Disable(primaryTable.Visual == 1,:) == 0);


sankeyStruct.visual.other = ...
    sum(primaryTable.Visual(primaryTable.Visual == 1,:) == 1) - ...
    sankeyStruct.visual.error - sankeyStruct.visual.posConflict - ...
    sankeyStruct.visual.negConflict - sankeyStruct.visual.disable - ...
    sankeyStruct.visual.enable - sankeyStruct.visual.visual;















